### ISSUE TITLE
env.reset() causing SimTK Exception thrown Error

### ISSUE THREAD

**Issue by yanpanlau** [stanfordnmbl/osim-rl#8]
I am trying to call env.reset() after 50 timestep but I got the following error:

std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &)': SimTK Exception thrown at AbstractIntegratorRep.cpp:428

Can you please advice how to reset the environment properly?
Thanks 
```
from osim.env import GaitEnv
env=GaitEnv(visualize=True)
observation env.reset()
print observation

for i in range(10000):
	print i
 	observation, reward, done, info	= env.step(env.action_space.sample())
	if (i == 50):
		env.reset()
```

**Comment by kidzik** [comment]
Thanks for your message!
This code should actually work. Are you using the precompiled OpenSim from the conda environment (https://anaconda.org/kidzik/opensim)? If not, and you're compiling from the source, please use the same version, i.e. the one from this commit https://github.com/opensim-org/opensim-core/tree/b3163b22be7bd4cccd8c073e02dd3abb52867031

Since we are using an alpha version of OpenSim 4.0 the exact commit matters.

**Comment by yanpanlau** [comment]
I just compile from source code "git clone opensim-core", which I think is the HEAD version. Does it mean the HEAD version is not compatible with osim-rl?

**Comment by kidzik** [comment]
Hi, the pre-alpha version of OpenSim is moving quickly and for the moment there are no cross-tests with osim-rl, so it might not be compatible unfortunately. In the current development phase, osim-rl was only tested with the OpenSim commit I mentioned. Yet, soon I will catch up with the more recent versions. Sorry for the inconvenience...
The simplest way to get everything up and running should be the conda environment. In any case thanks for running the package and reporting the problem

**Comment by yanpanlau** [comment]
I installed the particular branch that you suggest however it has the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/__init__.py", line 1, in <module>
    from simbody import *
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simbody.py", line 17, in <module>
    _simbody = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/opensim-4.0-py2.7.egg/opensim/simbody.py", line 16, in swig_import_helper
    return importlib.import_module('_simbody')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _simbody
```


(But in the unit-test after compile it said all the module can run OK)

**Comment by chrisdembia** [comment]
Are the Simbody shared libraries on the library path (e.g., LD_LIBRARY_PATH)?

**Comment by jeweljames** [comment]
@yanpanlau  Adding the dependencies' shared libraries to the library path fixes the 'No module named _simbody' error. 

@kidzik 
 Im facing the issue reported here too . The error :

> std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &,double)': SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
  Integrator step failed at time 0 apparently because:
SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
  Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 0.
  (Required condition 't1 > t0' was not met.)

continues to be thrown. 

After this error is thrown, env.reset() does not help . 
Defining a  new environment with 'env = GaitEnv()' does not help either.

**Comment by kidzik** [comment]
Is this error thrown right away or after some iterations? It can be caused by NaNs passed to the `step` function. Can you please write some details about the code you are running? Thanks!

**Comment by jeweljames** [comment]
I have build opensim from the above mentioned commit and i am running the example.py inside osim-rl's scripts folder with 

`python example.py --visualize --train --model sample`

The code breaks at some iteration after 100 iterations

The output is :
> Interval 1 (0 steps performed)
>   102/10000 [..............................] - ETA: 800s - reward: -0.0569
> 
> std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &,double)': SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
>   Integrator step failed at time 1.02 apparently because:
> SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
>   Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 1.02.
>   (Required condition 't1 > t0' was not met.)

> 103/10000 [..............................] - ETA: 808s - reward: -4.9107
> std::exception in 'bool OpenSim::Manager::integrate(SimTK::State &,double)': SimTK Exception thrown at AbstractIntegratorRep.cpp:428:
>   Integrator step failed at time 0 apparently because:
> SimTK Exception thrown at AbstractIntegratorRep.cpp:547:
>   Error detected by Simbody method AbstractIntegrator::takeOneStep(): Unable to advance time past 0.
>   (Required condition 't1 > t0' was not met.)

And the error will be thrown at each iteration. 

I read [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=7390&p=0&start=0&view=) that "the "Required condition 't1 > t0' was not met." message means that the integrator was trying to take a step (its first step at t = 1s, according to the exception message) but kept decreasing the step size to try to find an answer—and ultimately decreased the step to an unacceptably small size."

Is there anyway to avoid/handle this exception?

**Comment by kidzik** [comment]
Can you please check what parameter is passed to the `env.step()` function? If any coefficient is not between `0` and `1` or if it's `NaN`.
If the parameter is `NaN` then crashing is actually the expected behavior (although of course error message should be more meaningful and we will fix it).

Another place where I experienced this error was when I was running osim-rl with a more recent version of OpenSim (since reset of the model works differently there). You mentioned that you compiled from the commit I mentioned so it's good, but if you compiled it before with the recent version please double check if it's loading the right library. Thanks!

**Comment by harrykrish** [comment]
@kidzik Is this error posted by @jeweljames resolved now? If yes, could you please share the steps to resolve this?
Thanks!

**Comment by kishorekumarm** [comment]
@yanpanlau  @kidzik  Has this been resolved yet? 
Thanks!

**Comment by kidzik** [comment]
We still can't replicate the error. @harrykrish @kishorekumarm can you please give us details about the environment you are using (OS, python, versions of packages)? Are you using conda OpenSim package?

**Comment by kishorekumarm** [comment]
Thanks for the prompt response @kidzik  
OS: windows10
python: 2.7
keras-rl: 0.3.0
keras: 2.0.3
Theano: 0.9.0
opensim: 4.0

When we ran the following code:

from osim.env import GaitEnv
env=GaitEnv(visualize=True)
observation= env.reset()
#print observation

for i in range(100):
	#print i
 	observation, reward, done, info	= env.step(env.action_space.sample())
	print "sample"+str(i)+":"
	print env.action_space.sample()
	if (i == 50):
		env.reset()

Code breaks from 50th iteration:
![image](https://cloud.githubusercontent.com/assets/19287163/25397089/0a915844-29b5-11e7-8e1f-10237591c8d0.png)

**Comment by kishorekumarm** [comment]
@yanpanlau @kidzik Just noticed that this works perfectly fine with ubuntu.

**Comment by kidzik** [comment]
Thanks @kishorekumarm ! We will try to reproduce the error on Windows 10 and update the build.

**Comment by dzliu** [comment]
I'm having the exact same issue on both Mac and ubuntu. I receive the exact same error as mentioned above at iteration 50. Any idea how to resolve this issue? 

Another issue I'm having is that for some reason my env.action_space.sample() returns an empty list [], has anyone seen this problem before?

Thanks

**Comment by kidzik** [comment]
A clean conda installation (build 12) should now work well with the HEAD branch of https://github.com/stanfordnmbl/osim-rl . I tested it on Ubuntu and Windows. Please let me know if you still experience these errors.

**Comment by kidzik** [comment]
This should work with the current conda build (with the OpenSim 4.0 beta release).
